[global]
# time until the game ends [int]
playtime=-1
# seed for the RNG [int]
seed=73
# frames per second [int]
fps=60
# number of updates every frame [int]
speed=100
# number of seekers per player [int]
seekers=6
# number of goals [int]
goals=6
# color threshold for avoidance of similar colors [float]
color-threshold=0.1
# maximum sum of attracting/repulsing forces
total-magnet-resources=3

[map]
# map dimensions [int]
width=800
height=800

[camp]
# camp dimensions [int]
width=70
height=70

[seeker]
# length of the acceleration vector of a seeker [float]
thrust=0.1
# ratio of the thrust of a seeker when its magnet is active [float]
magnet-slowdown=0.2
# time until a seeker becomes active again [int]
disabled-time=250
# radius of a seeker [float]
radius=10
# mass of a seeker [float]
mass=1
# friction experienced by a seeker
friction=.02


[goal]
# time until a goal gets scored [int]
scoring-time=100
# radius of a goal [float]
radius=6
# mass of a goal [float]
mass=0.5
# factor that determines how strongly a goal is affected by a magnet [float]
thrust=0.05
# friction experienced by a goal
friction=.02
